package se.citerus.lookingfor.view.usermgmt;

import java.util.List;

import se.citerus.lookingfor.MainWindow;
import se.citerus.lookingfor.ViewSwitchListener;
import se.citerus.lookingfor.logic.UserHandler;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.Button.ClickEvent;

public class UserListView extends CustomComponent {
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button homeButton;
	@AutoGenerated
	private VerticalSplitPanel verticalSplitPanel_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button addButton;
	@AutoGenerated
	private Button editButton;
	@AutoGenerated
	private Button deleteButton;
	@AutoGenerated
	private Label filler_1;
	@AutoGenerated
	private Table userTable;
	private final ViewSwitchListener listener;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param listener 
	 */
	public UserListView(final ViewSwitchListener listener) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.listener = listener;
		homeButton.addListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				listener.switchToWelcomeView();
			}
		});
		
		userTable.addContainerProperty("Användarnamn/-roll", String.class, null); //TODO change to multi-col
		UserHandler userHandler = new UserHandler();
		List<String> listOfUsers = userHandler.getListOfUsers();
		int id = 0;
		for (String userString : listOfUsers) {
			//userTable.addItem(new Object[] {id++}).addItemProperty(id, new Property());
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalSplitPanel_1
		verticalSplitPanel_1 = buildVerticalSplitPanel_1();
		mainLayout.addComponent(verticalSplitPanel_1, "top:35.0px;left:0.0px;");
		
		// homeButton
		homeButton = new Button();
		homeButton.setCaption("Tillbaka");
		homeButton.setImmediate(true);
		homeButton.setWidth("-1px");
		homeButton.setHeight("-1px");
		mainLayout.addComponent(homeButton, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_1() {
		// common part: create layout
		verticalSplitPanel_1 = new VerticalSplitPanel();
		verticalSplitPanel_1.setImmediate(false);
		verticalSplitPanel_1.setWidth("50.0%");
		verticalSplitPanel_1.setHeight("50.0%");
		verticalSplitPanel_1.setMargin(false);
		
		// userList
		userTable = new Table("Användare");
		userTable.setImmediate(false);
		userTable.setWidth("100.0%");
		userTable.setHeight("100.0%");
		verticalSplitPanel_1.addComponent(userTable);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalSplitPanel_1.addComponent(horizontalLayout_2);
		
		return verticalSplitPanel_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("100.0%");
		horizontalLayout_2.setHeight("100.0%");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// filler_1
		filler_1 = new Label();
		filler_1.setImmediate(false);
		filler_1.setWidth("100.0%");
		filler_1.setHeight("-1px");
		filler_1.setValue(" ");
		horizontalLayout_2.addComponent(filler_1);
		horizontalLayout_2.setExpandRatio(filler_1, 1.0f);
		
		// deleteButton
		deleteButton = new Button();
		deleteButton.setCaption("Ta bort");
		deleteButton.setImmediate(true);
		deleteButton.setWidth("-1px");
		deleteButton.setHeight("-1px");
		horizontalLayout_2.addComponent(deleteButton);
		
		// editButton
		editButton = new Button();
		editButton.setCaption("Redigera");
		editButton.setImmediate(true);
		editButton.setWidth("-1px");
		editButton.setHeight("-1px");
		horizontalLayout_2.addComponent(editButton);
		
		// addButton
		addButton = new Button();
		addButton.setCaption("Lägg till");
		addButton.setImmediate(true);
		addButton.setWidth("-1px");
		addButton.setHeight("-1px");
		horizontalLayout_2.addComponent(addButton);
		
		return horizontalLayout_2;
	}
}
